version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: wc_server
    volumes:
      - ./public/:/var/www/html
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx
    ports:
      - 80:80
  php:
    image: php:8.1-fpm
    container_name: php
    volumes:
     - ./public/:/var/www/html
  wc_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: wc_db
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: wc_db
    container_name: wc_admin